server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    zipkin: http://localhost:9411
  data:
    mongodb:
      database: test
      uri: mongodb+srv://jointec:jointec@monnlech.jujo2t3.mongodb.net/?retryWrites=true&w=majority
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
