server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/bryanjesuscastro2003/springmicro
          search-paths: config-data
  application:
    name: config-server
